import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  Search: {
    width: "100%",
    height: 100,
  },
  Name: {
    width: "95%",
    height: 70,
    backgroundColor: "#414B51",
    borderRadius: 100,
    margin: "2.5%",
    fontSize: 20,
    fontFamily: "Pacifico_400Regular",
    paddingLeft: "2%",
  },
  Code: {
    width: "45%",
    height: 70,
    backgroundColor: "#414B51",
    borderRadius: 100,
    margin: "2.5%",
    fontSize: 20,
    fontFamily: "Pacifico_400Regular",
    paddingLeft: "2%",
  },
  Button: {
    width: "45%",
    height: 60,
    backgroundColor: "#414B51",
    borderRadius: 100,
    margin: "2.5%",
    alignContent: "center",
    justifyContent: "center",
    position: "absolute",
    top: 90,
    right: "0%",
  },
  ButtonText: {
    fontSize: 20,
    fontFamily: "Pacifico_400Regular",
    color: "#8C99A0",
    width: "100%",
    textAlign: "center",
  },
  hr: {
    width: "90%",
    height: 10,
    backgroundColor: "#414B51",
    marginHorizontal: "5%",
    borderRadius: 100,
  },
  loadingOverlay: {
    height: "65%",
    position: "absolute",
    top: "25%",
    width: "100%",
    alignContent: "center",
    justifyContent: "center",
  },
  PaperList: {
    height: "95%",
    width: "100%",
    top: 101,
  },
  PaperCardBase: {
    width: "95%",
    height: 150,
    left: "2.5%",
  },
  PaperCard: {
    width: "100%",
    height: "90%",
    borderRadius: 30,
    padding: "5%",
  },
  PaperCardName: {
    fontFamily: "Pacifico_400Regular",
    color: "#ffffff",
    position: "absolute",
    left: "5%",
    top: "15%",
    lineHeight: 50,
  },
  PaperCardType: {
    fontFamily: "IBMPlexMono_700Bold",
    color: "#ffffff",
    position: "absolute",
    right: "5%",
    top: "15%",
    lineHeight: 50,
    fontSize: 30,
  },
  PaperCardSession: {
    fontFamily: "Caveat_700Bold",
    color: "#ffffff",
    position: "absolute",
    left: "5%",
    top: "75%",
    lineHeight: 50,
    fontSize: 20,
  },
  PaperCardCode: {
    fontFamily: "IBMPlexMono_700Bold",
    color: "#ffffff",
    position: "absolute",
    right: "5%",
    top: "75%",
    lineHeight: 50,
    fontSize: 20,
  },
  divider: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 100,
    height: 5,
    top: "53%",
  },
});
export default styles;
