import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  userCardBase: {
    width: "75%",
    height: "30%",
    position: "absolute",
    top: "2%",
    left: "12.5%",
    justifyContent: "center",
    alignItems: "center",
  },
  displayPicture: {
    width: "70%",
    height: "80%",
    borderRadius: 200,
    position: "absolute",
    left: "15%",
    top: "5%",
  },
  userCardText: {
    position: "absolute",
    top: "85%",
    color: "white",
    textAlign: "center",
    width: "100%",
    fontFamily: "Pacifico_400Regular",
  },
  userStatCard: {
    width: "100%",
    height: "85%",
    position: "absolute",
    top: "23%",
    justifyContent: "center",
    alignItems: "center",
  },
  offlineCardBase: {
    width: "100%",
    height: "26.5%",
    position: "absolute",
    top: "54%",
    left: "3%",
    borderRadius: 30,
  },
  offlineCard: {
    width: "95%",
    height: "65%",
    borderRadius: 30,
    overflow: "hidden",
  },
  offlineCardText: {
    fontFamily: "Caveat_700Bold",
    color: "white",
    height: "100%",
    width: "95%",
    lineHeight: 80,
    fontSize: 45,
    position: "absolute",
    left: "10%",
    top: "15%",
  },
  offlineCardText2: {
    fontFamily: "IBMPlexMono_700Bold",
    color: "white",
    width: "100%",
    lineHeight: 80,
    fontSize: 30,
    top: "40%",
    position: "absolute",
    textAlign: "center",
  },
  Slider: {
    position: "absolute",
    top: "30%",
    right: "5%",
    height: "40%",
    width: "40%",
    backgroundColor: "#783A00",
    borderRadius: 100,
  },
  SliderBall: {
    position: "absolute",
    top: "10%",
    height: "80%",
    width: "30%",
    backgroundColor: "#FDC999",
    borderRadius: 200,
  },
  logoutCardBase: {
    width: "100%",
    height: "26.5%",
    position: "absolute",
    top: "72.5%",
    left: "3%",
    borderRadius: 30,
  },
  closeCardBase: {
    width: "100%",
    height: "12%",
    position: "absolute",
    top: "91%",
    left: "3%",
    borderRadius: 30,
  },
});
export default styles;
