import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  userStatCardBase: {
    width: "100%",
    height: "20%",
    position: "absolute",
    top: "5%",
    left: "0%",
    justifyContent: "center",
    alignItems: "center",
  },
  userCard: {
    width: "90%",
    height: "12%",
    position: "absolute",
    top: "1%",
    left: "5%",
    justifyContent: "center",
  },
  displayPicture: {
    width: "25%",
    height: "90%",
    borderRadius: 100,
  },
  userCardText: {
    position: "absolute",
    left: "30%",
    fontFamily: "Pacifico_400Regular",
    color: "white",
    height: "100%",
    width: "75%",
    lineHeight: 100,
  },
  userStatCard: {
    width: "95%",
    height: "100%",
    position: "absolute",
    top: "50%",
    left: "3%",
    borderRadius: 30,
    overflow: "hidden",
  },
  userStatCardText: {
    position: "absolute",
    left: "5%",
    top: "-5%",
    fontFamily: "Pacifico_400Regular",
    color: "white",
    height: "100%",
    width: "75%",
    lineHeight: 100,
    fontSize: 25,
  },
  userStatCardText2: {
    position: "absolute",
    left: "5%",
    top: "25%",
    fontFamily: "Caveat_700Bold",
    color: "white",
    height: "100%",
    width: "75%",
    lineHeight: 100,
    fontSize: 25,
  },
  userStatCardImage: {
    position: "absolute",
    right: "5%",
    width: "30%",
    height: "100%",
    marginTop: "4%",
  },
  paperCardBase: {
    width: "45%",
    height: "30%",
    position: "absolute",
    top: "37%",
    left: "3%",
    borderRadius: 30,
  },
  paperCard: {
    width: "100%",
    height: "65%",
    borderRadius: 30,
    overflow: "hidden",
  },
  paperCardText: {
    fontFamily: "Caveat_700Bold",
    color: "white",
    height: "100%",
    width: "95%",
    lineHeight: 80,
    fontSize: 30,
    position: "absolute",
    textAlign: "center",
  },
  paperCardText2: {
    fontFamily: "IBMPlexMono_700Bold",
    color: "white",
    width: "100%",
    lineHeight: 80,
    fontSize: 30,
    top: "40%",
    position: "absolute",
    textAlign: "center",
  },
  attendanceCardBase: {
    width: "45%",
    height: "30%",
    position: "absolute",
    top: "37%",
    left: "53%",
    borderRadius: 30,
  },
  attendanceCardText2: {
    fontFamily: "IBMPlexMono_700Bold",
    color: "white",
    width: "100%",
    lineHeight: 80,
    fontSize: 20,
    top: "27%",
    position: "absolute",
    textAlign: "center",
  },
  attendanceCardBarBase: {
    width: "90%",
    height: "15%",
    position: "absolute",
    top: "70%",
    left: "5%",
    borderRadius: 30,
    backgroundColor: "#AC4AC5",
  },
  attendanceCardBar: {
    height: "15%",
    position: "absolute",
    top: "70%",
    left: "5%",
    borderRadius: 30,
    backgroundColor: "#F5CDFF",
  },
  quoteCardBase: {
    width: "100%",
    height: "30%",
    position: "absolute",
    top: "43%",
    left: "0%",
    borderRadius: 30,
  },
  quoteCardText: {
    fontFamily: "Pacifico_400Regular",
    color: "white",
    width: "100%",
    lineHeight: 80,
    fontSize: 30,
    position: "absolute",
    textAlign: "center",
  },
  quoteCardText2: {
    fontFamily: "Pacifico_400Regular",
    color: "white",
    width: "100%",
    lineHeight: 25,
    fontSize: 15,
    position: "absolute",
    textAlign: "center",
    top:"35%"
  },
});
export default styles;
